repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: prom-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url:  https://grafana.github.io/helm-charts
  - name: longhorn
    url: https://charts.longhorn.io
  - name: hashicorp
    url: https://helm.releases.hashicorp.com
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: banzai
    url: https://kubernetes-charts.banzaicloud.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: mariadb
    url: git+https://github.com/aldor007/mariadb-operator@charts
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: kong
    url: https://charts.konghq.com



environments:
  default:
    secrets:
      - env/secrets.yaml

helmDefaults:
  tillerless: true
  cleanupOnFail: true              #dedicated default key for helm flag --cleanup-on-fail
  timeout: 1000
  # forces resource update through delete/recreate if needed (default false)
  force: false
  # limit the maximum number of revisions saved per release. Use 0 for no limit. (default 10)
  historyMax: 10
  verify: false

# helmBinary: .bin/helm"

releases:
  - name: metallb
    chart: ./charts/metallb
    hooks:
      - events: ["prepare", "cleanup"]
        command: ".bin/helmify"
        args: ["{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}", "{{`{{.Release.Chart}}`}}", "{{`{{.Environment.Name}}`}}"]
      # - events: ["presync"]
      #   args: ["-c", "kubectl get secrets -n metallb-system  memberlist  >/dev/null 2>&1  || kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey=\"$(openssl rand -base64 128)\""]
  - name: monitoring
    namespace: monitoring
    chart: ./charts/prometheus-operator
    version: 0.5.0
    force: false
    values:
      - values/prometheus-operator.yaml
    hooks:
    - events: ["presync"]
      command: "/bin/sh"
      args: ["-c", "kubectl apply -f  charts/prometheus-operator/crds/ || kubectl replace -f charts/prometheus-operator/crds/ "]
    - events: ["presync"]
      command: "/bin/sh"
      args: ["-c", "./scripts/patch-ns-monitoring.sh"]
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: 9.11.0
    values:
      - values/traefik.yaml
  - name: kong
    namespace: ingress
    chart: charts/kong
    version: 2.7.0
    values:
      - values/kong.yaml
  - name: nfs-cubie2
    namespace: nfs-provisioner
    chart: ./charts/nfs-subdir-external-provisioner
    values:
      - values/nfs.yaml
      - values/nfs-cubie2.yaml
  - name: nfs-nas
    namespace: nfs-provisioner
    chart: ./charts/nfs-subdir-external-provisioner
    values:
      - values/nfs.yaml
      - values/nfs-nas.yaml
  - name: redis-1
    namespace: redis
    chart: bitnami/redis
    version: 12.8.0
    values:
      - values/redis.yaml
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.1.0
    hooks:
    - events: ["presync"]
      command: "/bin/sh"
      args: ["-c", "kubectl apply -f  https://github.com/jetstack/cert-manager/releases/download/v1.1.0/cert-manager.crds.yaml"]
  - name: ca-certs
    namespace: cert-manager
    chart: ./charts/certs
    version: 1.1.0
  - name: vault-operator
    namespace: vault
    chart: banzai/vault-operator
    version: 1.9.2
    values:
      - values/vault-operator.yaml
  - name: vault-secrets-webhook
    namespace: vault
    chart: banzai/vault-secrets-webhook
    version: 1.11.2
  - name: vault
    namespace: vault
    chart:  ./charts/vault
    version: 1.9.2
  - name: argocd
    namespace: argocd
    chart:  ./charts/argocd-m39
    version: 0.1.0
    values:
      - values/argocd.yaml.gotmpl
  - name: argocd-apps
    namespace: argocd
    chart:  ./charts/argocd-apps
    version: 0.1.0
  - name: mariadb-operator
    namespace: mariadb
    chart: mariadb/mariadb-operator
    version: 0.1.0
  - name: cloudflared-credentials
    namespace: cloudflare
    chart:  ./charts/cloudflare-creds
    version: 0.1.0
    values:
      - config: |-
          {{ .Values.cloudflareTunnelData }}
  - name: cloudflared
    namespace: cloudflare
    chart:  ./charts/cloudflared
    version: 0.3.3
    values:
      - values/cloudflared.yaml

  # longhorn is not working on A10/A20 - cubie
  # - name: longhorn
  #   namespace: longhorn-system
  #   chart: longhorn/longhorn
  #   version: 1.1.0
  #   values:
  #     - values/longhorn.yaml


