apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: purge-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:aldor007/argo-apps.git'
    targetRevision: HEAD
    path: purge-api
  destination:
    server: https://kubernetes.default.svc
    namespace: mkaciuba
  syncPolicy:
    automated:
      prune:  false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy