{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mort.fullname" . }}-env-secrets
  labels:
    {{- include "mort.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.env }}
    {{ $key }}: {{ $value | b64enc | quote}}
  {{- end }}
{{- end }}
