apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-prometheus-operator
  labels:
    {{- include "mort.labels" . | nindent 4 }}
    monitoring: prometheus
spec:
  selector:
    matchLabels:
    {{- include "mort.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    path: /metrics