---
language: python

# Use the new container infrastructure
sudo: required

env:
  global:
    - ROLE_NAME: bind
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian8
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu2004

# Enable docker support
services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install bats curl dnsutils
  # Install dependencies for Molecule test
  - python3 -m pip install molecule yamllint ansible-lint docker netaddr dnspython
  # Check ansible and molecule version
  - ansible --version
  - molecule --version

script:
  # Run molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
