apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mkaciuba.fullname" . }}-tmp-pvc
  labels:
    {{- include "mkaciuba.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas
  resources:
    requests:
      storage: 7Gi