apiVersion: v1
kind: Secret
metadata:
    name: mariadb-mkaciuba
type: Opaque
data:
    rootPassword: {{.Values.database.rootPassword | b64enc }}
    strapiPassword: {{ .Values.database.strapiPassword | b64enc}}