apiVersion: v1
kind: Service
metadata:
  name: {{ include "mkaciuba.fullname" . }}-strapi
  labels:
    {{- include "mkaciuba.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    tier: mkaciuba-backend
