apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "greebo.fullname" . }}-config
  labels:
    {{- include "greebo.labels" . | nindent 4 }}
data:
    config.yml: |-
{{ (.Files.Get "files/config.yaml") |  nindent 6 }}