
- name: Install  python3-rpi.gpio
  package:
    name:  python3-rpi.gpio
    state: present

- name: Install python3-systemd
  package:
    name:  python3-systemd
    state: present
- 
- name: Copy systemd service file to server
  copy:
    src: temp.service
    dest: /etc/systemd/system
    owner: root
    group: root

- name: Copy binary to server
  copy:
    src: rasp.py
    dest: /usr/local/bin/rasp.py
    mode: 0755
    owner: root
    group: root

- name: Start temp
  ansible.builtin.systemd:
    name: temp.service
    enabled: yes
    masked: no