apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "insti.fullname" . }}-pvc
  labels:
    {{- include "insti.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas
  resources:
    requests:
      storage: 1024Mi