{{- if and .Values.podMonitor.enabled .Values.podMonitor.metricsEndpoints }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cloudflared.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.podMonitor.extraLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  {{- toYaml .Values.podMonitor.metricsEndpoints | nindent 2 }}
{{- end }}
