apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: vault
spec:
  commonName: m39 k8s cluster
  duration: 14400h 
  renewBefore: 62h
  dnsNames:
    - "*.k8s.m39"
    - "*.m39" 
  secretName: selfsigned-cert
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io